#!/bin/bash

# @Name		 
# @Author	Oliver Avarello
# @Version	29.01.2018
# @Snapshort	1.0.0
# 
# Description:
#	starten die javaFx view 

# clean - Loeschen aller erzeugten Artefakte und des target-Verzeichnisses
# jfx:run - ist ein plugin das Build und Erzeugung der Ergebnis-Artefakte
# 			und starten das user Interface mit Javafx

mvn clean jfx:run